---

- name: Tomcat playbook
  hosts: webserver
  become: true
  become_user: root
  # this is tasks section
  tasks:
  - name: Install tomcat on host server
    yum: name=tomcat state=present
  - name: Start the tomcat service on the host server
    service: name=tomcat state=started
  - name: Deploy a war file on tomcat webapps directory
    get_url:
      url=https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
      dest=/usr/share/tomcat/webapps
  - name: restart the tomcat service
    service: name=tomcat state=restarted
